apiVersion: v1
kind: Secret

metadata:
  name: paciente-secret

type: Opaque

stringData:
  DB_HOST: postgres-paciente-service
  DB_PORT: "5432"
  DB_NAME: paciente_db
  DB_USER: postgres
  DB_PASSWORD: "123456"
